services:
  mongo:
    image: mongo:6
    container_name: expense_tracker_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: expenses

  mongo-express:
    image: mongo-express
    container_name: expense_tracker_mongo_express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    container_name: expense_tracker_backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      MONGO_URI: mongodb://mongo:27017/expenses
    depends_on:
      - mongo

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    container_name: expense_tracker_frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      VITE_BACKEND_URL: http://backend:3000/graphql
    depends_on:
      - backend

volumes:
  mongo-data:
